[package]
name = "yasl"
description = "yet another spotifyd listener"
version = "0.1.0"
authors = ["Vinicius Moura Longaray <vmouralongaray@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dbus = "0.9.*"
